### ISSUE TITLE
[VnV standalone monitoring API ]

### ISSUE THREAD

**Issue by sinaure** [sonata-nfv/son-monitor#138]
monitoring api points to a pre-int-vnv-bcn.5gtango.eu instead of our internal address

message:172.18.0.15 - - [21/Nov/2019:15:37:41 +0000] "GET **/api/v3/monitoring/graphs/d-solo/sp_dash/sp**?orgId=1&panelId=2&var-id=4fd837f6-5f49-11dc-a9ed-000ea629289b&var-entity=vm&var-env=pre-int-vnv-bcn.5gtango.eu%3A4fd837f6-5f49-11dc-a9ed-000ea629289b&theme=light&refresh=10s HTTP/1.0" 200 - 0.3487 container_name:tng-api-gtw host:VV_5GTango source_host:192.168.1.181 level:3 created:November 14th 2019, 18:07:24.852 type:logs version:1.1 command:bundle exec rackup -p 5000 --host 0.0.0.0 image_name:sonatanfv/tng-api-gtw:v5.0 @timestamp:November 21st 2019, 16:37:41.446 @version:1

**Comment by sinaure** [comment]
#https://github.com/sonata-nfv/tng-api-gtw/issues/230

**Comment by pkarkazis** [comment]
This query is originated from the portal asking a graph from monitoring (via tng-api-gtw). 
@anapolg could you please take a look at this?

**Comment by anapolg** [comment]
Yes, I already took a look in https://github.com/sonata-nfv/tng-portal/issues/466

**Comment by pkarkazis** [comment]
Thanks for the quick response

**Comment by sinaure** [comment]
ok I close it and re open it on tng-portal
