### ISSUE TITLE
Integration test 8 is failing

### ISSUE THREAD

**Issue by felipevicens** [sonata-nfv/son-monitor#22]
Hello the integration test 8 have the following error:

03:37:57 docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:53: mounting \\\\\\\"/home/jenkins/workspace/int-8-sdk-son-monitor/misc/prometheus_jenkins.yml\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/aufs/mnt/97d60da71fdbeebea7675cb5449835a564031e2f7450ce14725d3f7b6d0dcfbd\\\\\\\" at \\\\\\\"/var/lib/docker/aufs/mnt/97d60da71fdbeebea7675cb5449835a564031e2f7450ce14725d3f7b6d0dcfbd **/etc/prometheus/prometheus.yml\\\\\\\" caused \\\\\\\"not a directory\\\\\\\"\\\"\"\n".**

More information:
https://jenkins.sonata-nfv.eu/view/INTEGRATION/job/int-8-sdk-son-monitor/327/console

**Comment by pkarkazis** [comment]
The int-8-sdk-on-monitor test has to do with test between son-emulator and its own instances of prometheus and pushgateway.
