### ISSUE TITLE
SLM still receiving monitoring data for deleted services

### ISSUE THREAD

**Issue by tsoenen** [sonata-nfv/son-monitor#32]
I have noticed that the Monitoring Manager is still sending monitoring information of services that have been deleted by executing a `DELETE` on the url `<base_monitoring_link>/<service_instance_uuid>`, which responded with a `204` message.

**Comment by pkarkazis** [comment]
Hello @tsoenen,
do you mean that you are getting notifications after the deletion the VNFs which consist the deleted service?
